package shattered.lib;

import static org.lwjgl.glfw.GLFW.GLFW_KEY_0;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_1;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_2;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_3;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_4;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_5;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_6;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_7;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_8;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_9;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_A;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_APOSTROPHE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_B;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_BACKSLASH;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_BACKSPACE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_C;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_CAPS_LOCK;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_COMMA;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_D;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_DELETE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_DOWN;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_E;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_END;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_ENTER;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_EQUAL;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_ESCAPE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F1;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F10;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F11;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F12;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F13;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F14;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F15;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F16;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F17;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F18;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F19;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F2;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F20;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F21;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F22;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F23;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F24;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F25;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F3;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F4;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F5;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F6;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F7;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F8;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_F9;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_G;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_GRAVE_ACCENT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_H;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_HOME;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_I;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_INSERT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_J;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_K;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_0;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_1;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_2;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_3;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_4;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_5;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_6;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_7;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_8;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_9;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_ADD;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_DECIMAL;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_DIVIDE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_ENTER;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_EQUAL;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_MULTIPLY;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_KP_SUBTRACT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_L;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_ALT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_BRACKET;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_CONTROL;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_SHIFT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_LEFT_SUPER;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_M;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_MENU;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_MINUS;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_N;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_NUM_LOCK;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_O;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_P;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_PAGE_DOWN;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_PAGE_UP;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_PAUSE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_PERIOD;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_PRINT_SCREEN;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_Q;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_R;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_ALT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_BRACKET;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_CONTROL;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_SHIFT;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_RIGHT_SUPER;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_S;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_SCROLL_LOCK;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_SEMICOLON;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_SLASH;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_SPACE;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_T;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_TAB;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_U;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_UNKNOWN;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_UP;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_V;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_W;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_X;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_Y;
import static org.lwjgl.glfw.GLFW.GLFW_KEY_Z;

final class KeyboardHelper {

	private KeyboardHelper() {
	}

	public static void addKeyNames() {
		Input.KEY_NAMES.put(GLFW_KEY_UNKNOWN, "[?]");
		Input.KEY_NAMES.put(GLFW_KEY_SPACE, "Space");
		Input.KEY_NAMES.put(GLFW_KEY_APOSTROPHE, "Quote");
		Input.KEY_NAMES.put(GLFW_KEY_COMMA, "Comma");
		Input.KEY_NAMES.put(GLFW_KEY_MINUS, "Minus");
		Input.KEY_NAMES.put(GLFW_KEY_PERIOD, "Period");
		Input.KEY_NAMES.put(GLFW_KEY_SLASH, "Slash");
		Input.KEY_NAMES.put(GLFW_KEY_0, "0");
		Input.KEY_NAMES.put(GLFW_KEY_1, "1");
		Input.KEY_NAMES.put(GLFW_KEY_2, "2");
		Input.KEY_NAMES.put(GLFW_KEY_3, "3");
		Input.KEY_NAMES.put(GLFW_KEY_4, "4");
		Input.KEY_NAMES.put(GLFW_KEY_5, "5");
		Input.KEY_NAMES.put(GLFW_KEY_6, "6");
		Input.KEY_NAMES.put(GLFW_KEY_7, "7");
		Input.KEY_NAMES.put(GLFW_KEY_8, "8");
		Input.KEY_NAMES.put(GLFW_KEY_9, "9");
		Input.KEY_NAMES.put(GLFW_KEY_SEMICOLON, "Semicolon");
		Input.KEY_NAMES.put(GLFW_KEY_EQUAL, "Equals");
		Input.KEY_NAMES.put(GLFW_KEY_A, "a");
		Input.KEY_NAMES.put(GLFW_KEY_B, "b");
		Input.KEY_NAMES.put(GLFW_KEY_C, "c");
		Input.KEY_NAMES.put(GLFW_KEY_D, "d");
		Input.KEY_NAMES.put(GLFW_KEY_E, "e");
		Input.KEY_NAMES.put(GLFW_KEY_F, "f");
		Input.KEY_NAMES.put(GLFW_KEY_G, "g");
		Input.KEY_NAMES.put(GLFW_KEY_H, "h");
		Input.KEY_NAMES.put(GLFW_KEY_I, "i");
		Input.KEY_NAMES.put(GLFW_KEY_J, "j");
		Input.KEY_NAMES.put(GLFW_KEY_K, "k");
		Input.KEY_NAMES.put(GLFW_KEY_L, "l");
		Input.KEY_NAMES.put(GLFW_KEY_M, "m");
		Input.KEY_NAMES.put(GLFW_KEY_N, "n");
		Input.KEY_NAMES.put(GLFW_KEY_O, "o");
		Input.KEY_NAMES.put(GLFW_KEY_P, "p");
		Input.KEY_NAMES.put(GLFW_KEY_Q, "q");
		Input.KEY_NAMES.put(GLFW_KEY_R, "r");
		Input.KEY_NAMES.put(GLFW_KEY_S, "s");
		Input.KEY_NAMES.put(GLFW_KEY_T, "t");
		Input.KEY_NAMES.put(GLFW_KEY_U, "u");
		Input.KEY_NAMES.put(GLFW_KEY_V, "v");
		Input.KEY_NAMES.put(GLFW_KEY_W, "w");
		Input.KEY_NAMES.put(GLFW_KEY_X, "x");
		Input.KEY_NAMES.put(GLFW_KEY_Y, "y");
		Input.KEY_NAMES.put(GLFW_KEY_Z, "z");
		Input.KEY_NAMES.put(GLFW_KEY_LEFT_BRACKET, "Left bracked");
		Input.KEY_NAMES.put(GLFW_KEY_BACKSLASH, "Backslash");
		Input.KEY_NAMES.put(GLFW_KEY_RIGHT_BRACKET, "Bracked");
		Input.KEY_NAMES.put(GLFW_KEY_GRAVE_ACCENT, "Grave");
		Input.KEY_NAMES.put(GLFW_KEY_ESCAPE, "Escape");
		Input.KEY_NAMES.put(GLFW_KEY_ENTER, "Enter");
		Input.KEY_NAMES.put(GLFW_KEY_TAB, "Tab");
		Input.KEY_NAMES.put(GLFW_KEY_BACKSPACE, "Backspace");
		Input.KEY_NAMES.put(GLFW_KEY_INSERT, "Insert");
		Input.KEY_NAMES.put(GLFW_KEY_DELETE, "Delete");
		Input.KEY_NAMES.put(GLFW_KEY_RIGHT, "Arrow right");
		Input.KEY_NAMES.put(GLFW_KEY_LEFT, "Arrow left");
		Input.KEY_NAMES.put(GLFW_KEY_DOWN, "Arrow down");
		Input.KEY_NAMES.put(GLFW_KEY_UP, "Arrow up");
		Input.KEY_NAMES.put(GLFW_KEY_PAGE_UP, "Page up");
		Input.KEY_NAMES.put(GLFW_KEY_PAGE_DOWN, "Page down");
		Input.KEY_NAMES.put(GLFW_KEY_HOME, "Home");
		Input.KEY_NAMES.put(GLFW_KEY_END, "End");
		Input.KEY_NAMES.put(GLFW_KEY_CAPS_LOCK, "Caps Lock");
		Input.KEY_NAMES.put(GLFW_KEY_SCROLL_LOCK, "Scroll Lock");
		Input.KEY_NAMES.put(GLFW_KEY_NUM_LOCK, "Num Lock");
		Input.KEY_NAMES.put(GLFW_KEY_PRINT_SCREEN, "PrintScreen");
		Input.KEY_NAMES.put(GLFW_KEY_PAUSE, "Pause");
		Input.KEY_NAMES.put(GLFW_KEY_F1, "F1");
		Input.KEY_NAMES.put(GLFW_KEY_F2, "F2");
		Input.KEY_NAMES.put(GLFW_KEY_F3, "F3");
		Input.KEY_NAMES.put(GLFW_KEY_F4, "F4");
		Input.KEY_NAMES.put(GLFW_KEY_F5, "F5");
		Input.KEY_NAMES.put(GLFW_KEY_F6, "F6");
		Input.KEY_NAMES.put(GLFW_KEY_F7, "F7");
		Input.KEY_NAMES.put(GLFW_KEY_F8, "F8");
		Input.KEY_NAMES.put(GLFW_KEY_F9, "F9");
		Input.KEY_NAMES.put(GLFW_KEY_F10, "F10");
		Input.KEY_NAMES.put(GLFW_KEY_F11, "F11");
		Input.KEY_NAMES.put(GLFW_KEY_F12, "F12");
		Input.KEY_NAMES.put(GLFW_KEY_F13, "F13");
		Input.KEY_NAMES.put(GLFW_KEY_F14, "F14");
		Input.KEY_NAMES.put(GLFW_KEY_F15, "F15");
		Input.KEY_NAMES.put(GLFW_KEY_F16, "F16");
		Input.KEY_NAMES.put(GLFW_KEY_F17, "F17");
		Input.KEY_NAMES.put(GLFW_KEY_F18, "F18");
		Input.KEY_NAMES.put(GLFW_KEY_F19, "F19");
		Input.KEY_NAMES.put(GLFW_KEY_F20, "F20");
		Input.KEY_NAMES.put(GLFW_KEY_F21, "F21");
		Input.KEY_NAMES.put(GLFW_KEY_F22, "F22");
		Input.KEY_NAMES.put(GLFW_KEY_F23, "F23");
		Input.KEY_NAMES.put(GLFW_KEY_F24, "F24");
		Input.KEY_NAMES.put(GLFW_KEY_F25, "F25");
		Input.KEY_NAMES.put(GLFW_KEY_KP_0, "Numpad 0");
		Input.KEY_NAMES.put(GLFW_KEY_KP_1, "Numpad 1");
		Input.KEY_NAMES.put(GLFW_KEY_KP_2, "Numpad 2");
		Input.KEY_NAMES.put(GLFW_KEY_KP_3, "Numpad 3");
		Input.KEY_NAMES.put(GLFW_KEY_KP_4, "Numpad 4");
		Input.KEY_NAMES.put(GLFW_KEY_KP_5, "Numpad 5");
		Input.KEY_NAMES.put(GLFW_KEY_KP_6, "Numpad 6");
		Input.KEY_NAMES.put(GLFW_KEY_KP_7, "Numpad 7");
		Input.KEY_NAMES.put(GLFW_KEY_KP_8, "Numpad 8");
		Input.KEY_NAMES.put(GLFW_KEY_KP_9, "Numpad 9");
		Input.KEY_NAMES.put(GLFW_KEY_KP_DECIMAL, "Decimal");
		Input.KEY_NAMES.put(GLFW_KEY_KP_DIVIDE, "Divide");
		Input.KEY_NAMES.put(GLFW_KEY_KP_MULTIPLY, "Multiply");
		Input.KEY_NAMES.put(GLFW_KEY_KP_SUBTRACT, "Subtract");
		Input.KEY_NAMES.put(GLFW_KEY_KP_ADD, "Add");
		Input.KEY_NAMES.put(GLFW_KEY_KP_ENTER, "Numpad enter");
		Input.KEY_NAMES.put(GLFW_KEY_KP_EQUAL, "Numpad equals");
		Input.KEY_NAMES.put(GLFW_KEY_LEFT_SHIFT, "Shift (L)");
		Input.KEY_NAMES.put(GLFW_KEY_LEFT_CONTROL, "Control (L)");
		Input.KEY_NAMES.put(GLFW_KEY_LEFT_ALT, "Alt (L)");
		Input.KEY_NAMES.put(GLFW_KEY_LEFT_SUPER, "Meta (L)");
		Input.KEY_NAMES.put(GLFW_KEY_RIGHT_SHIFT, "Shift (R)");
		Input.KEY_NAMES.put(GLFW_KEY_RIGHT_CONTROL, "Control (R)");
		Input.KEY_NAMES.put(GLFW_KEY_RIGHT_ALT, "Alt (R)");
		Input.KEY_NAMES.put(GLFW_KEY_RIGHT_SUPER, "Meta (R)");
		Input.KEY_NAMES.put(GLFW_KEY_MENU, "Menu");

	}

	public static void addKeyChars() {
		Input.KEY_CHARS.put(GLFW_KEY_SPACE, new Character[]{' ', ' '});
		Input.KEY_CHARS.put(GLFW_KEY_APOSTROPHE, new Character[]{'\'', '"'});
		Input.KEY_CHARS.put(GLFW_KEY_COMMA, new Character[]{',', '<'});
		Input.KEY_CHARS.put(GLFW_KEY_MINUS, new Character[]{'-', '_'});
		Input.KEY_CHARS.put(GLFW_KEY_PERIOD, new Character[]{'.', '>'});
		Input.KEY_CHARS.put(GLFW_KEY_SLASH, new Character[]{'/', '?'});
		Input.KEY_CHARS.put(GLFW_KEY_0, new Character[]{'0', ')'});
		Input.KEY_CHARS.put(GLFW_KEY_1, new Character[]{'1', '!'});
		Input.KEY_CHARS.put(GLFW_KEY_2, new Character[]{'2', '@'});
		Input.KEY_CHARS.put(GLFW_KEY_3, new Character[]{'3', '#'});
		Input.KEY_CHARS.put(GLFW_KEY_4, new Character[]{'4', '$'});
		Input.KEY_CHARS.put(GLFW_KEY_5, new Character[]{'5', '%'});
		Input.KEY_CHARS.put(GLFW_KEY_6, new Character[]{'6', '^'});
		Input.KEY_CHARS.put(GLFW_KEY_7, new Character[]{'7', '&'});
		Input.KEY_CHARS.put(GLFW_KEY_8, new Character[]{'8', '*'});
		Input.KEY_CHARS.put(GLFW_KEY_9, new Character[]{'9', '('});
		Input.KEY_CHARS.put(GLFW_KEY_SEMICOLON, new Character[]{';', ':'});
		Input.KEY_CHARS.put(GLFW_KEY_EQUAL, new Character[]{'=', '+'});
		Input.KEY_CHARS.put(GLFW_KEY_A, new Character[]{'a', 'A'});
		Input.KEY_CHARS.put(GLFW_KEY_B, new Character[]{'b', 'B'});
		Input.KEY_CHARS.put(GLFW_KEY_C, new Character[]{'c', 'C'});
		Input.KEY_CHARS.put(GLFW_KEY_D, new Character[]{'d', 'D'});
		Input.KEY_CHARS.put(GLFW_KEY_E, new Character[]{'e', 'E'});
		Input.KEY_CHARS.put(GLFW_KEY_F, new Character[]{'f', 'F'});
		Input.KEY_CHARS.put(GLFW_KEY_G, new Character[]{'g', 'G'});
		Input.KEY_CHARS.put(GLFW_KEY_H, new Character[]{'h', 'H'});
		Input.KEY_CHARS.put(GLFW_KEY_I, new Character[]{'i', 'I'});
		Input.KEY_CHARS.put(GLFW_KEY_J, new Character[]{'j', 'J'});
		Input.KEY_CHARS.put(GLFW_KEY_K, new Character[]{'k', 'K'});
		Input.KEY_CHARS.put(GLFW_KEY_L, new Character[]{'l', 'L'});
		Input.KEY_CHARS.put(GLFW_KEY_M, new Character[]{'m', 'M'});
		Input.KEY_CHARS.put(GLFW_KEY_N, new Character[]{'n', 'N'});
		Input.KEY_CHARS.put(GLFW_KEY_O, new Character[]{'o', 'O'});
		Input.KEY_CHARS.put(GLFW_KEY_P, new Character[]{'p', 'P'});
		Input.KEY_CHARS.put(GLFW_KEY_Q, new Character[]{'q', 'Q'});
		Input.KEY_CHARS.put(GLFW_KEY_R, new Character[]{'r', 'R'});
		Input.KEY_CHARS.put(GLFW_KEY_S, new Character[]{'s', 'S'});
		Input.KEY_CHARS.put(GLFW_KEY_T, new Character[]{'t', 'T'});
		Input.KEY_CHARS.put(GLFW_KEY_U, new Character[]{'u', 'U'});
		Input.KEY_CHARS.put(GLFW_KEY_V, new Character[]{'v', 'V'});
		Input.KEY_CHARS.put(GLFW_KEY_W, new Character[]{'w', 'W'});
		Input.KEY_CHARS.put(GLFW_KEY_X, new Character[]{'x', 'X'});
		Input.KEY_CHARS.put(GLFW_KEY_Y, new Character[]{'y', 'Y'});
		Input.KEY_CHARS.put(GLFW_KEY_Z, new Character[]{'z', 'Z'});
		Input.KEY_CHARS.put(GLFW_KEY_LEFT_BRACKET, new Character[]{'[', '{'});
		Input.KEY_CHARS.put(GLFW_KEY_BACKSLASH, new Character[]{'\\', '|'});
		Input.KEY_CHARS.put(GLFW_KEY_RIGHT_BRACKET, new Character[]{']', '}'});
		Input.KEY_CHARS.put(GLFW_KEY_GRAVE_ACCENT, new Character[]{'`', '~'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_0, new Character[]{'0', '0'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_1, new Character[]{'1', '1'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_2, new Character[]{'2', '2'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_3, new Character[]{'3', '3'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_4, new Character[]{'4', '4'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_5, new Character[]{'5', '5'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_6, new Character[]{'6', '6'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_7, new Character[]{'7', '7'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_8, new Character[]{'8', '8'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_9, new Character[]{'9', '9'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_DECIMAL, new Character[]{'.', '.'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_DIVIDE, new Character[]{'/', '/'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_MULTIPLY, new Character[]{'*', '*'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_SUBTRACT, new Character[]{'-', '-'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_ADD, new Character[]{'+', '+'});
		Input.KEY_CHARS.put(GLFW_KEY_KP_EQUAL, new Character[]{'=', '='});
	}
}